services:
  export-html:

    platform: linux/amd64
    user: root
    environment:
      - PUPPETEER_CACHE_DIR=/home/pptruser/.cache/puppeteer
      - BIND_HOST=0.0.0.0
      - BIND_PORT=2305
      - ENV_NAME=development
      - GOOGLE_CLOUD_LOGGING=false
    volumes:
      - ./src:/service/src
      - ./data:/service/data
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2305:2305"
