services:
  export-html:
    container_name: export-carousel
    platform: linux/amd64
    volumes:
      - ./src:/service/src
      - ./data:/service/data
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2305:2305"
